// Define the interface for the Post
interface Post {
  img: string[];
  name: string;
  caption: string;
  location: string;
  likes: number;
  comments: string[];
  shares: number;
  bookmarked: boolean;
  Dietary: "veg" | "non-veg";
  Cuisine: "italian" | "indian" | "mexican" | "korean" | "japanese";
  mealType: "dinner" | "lunch" | "breakfast";
  tags: string[];
  createdAt: Date; // or Date if you want to use Date objects
}

// Array of available image URLs
const imageUrls = [
  "https://honest-bite-be.s3.amazonaws.com/FF.png",
  "https://honest-bite-be.s3.amazonaws.com/Lasagna.jpg",
  "https://honest-bite-be.s3.amazonaws.com/QUESADILLA.jpg",
  "https://honest-bite-be.s3.amazonaws.com/alfajor-latino.jpg",
  "https://honest-bite-be.s3.amazonaws.com/apple-pie.jpg",
  "https://honest-bite-be.s3.amazonaws.com/bagel-sandwich.jpg",
  "https://honest-bite-be.s3.amazonaws.com/bhelpuri.jpg",
  "https://honest-bite-be.s3.amazonaws.com/biryani.jpg",
  "https://honest-bite-be.s3.amazonaws.com/burger.jpg",
  "https://honest-bite-be.s3.amazonaws.com/chole-bhature.jpg",
  "https://honest-bite-be.s3.amazonaws.com/creme-brulee.jpg",
  "https://honest-bite-be.s3.amazonaws.com/dhokla.jpg",
  "https://honest-bite-be.s3.amazonaws.com/dosa.jpg",
  "https://honest-bite-be.s3.amazonaws.com/fafafel.jpg",
  "https://honest-bite-be.s3.amazonaws.com/gulab-jamun.jpg",
  "https://honest-bite-be.s3.amazonaws.com/idli-medu-vada.jpg",
  "https://honest-bite-be.s3.amazonaws.com/idli-with-sambar.jpg",
  "https://honest-bite-be.s3.amazonaws.com/korean-food-teokbokki.jpg",
  "https://honest-bite-be.s3.amazonaws.com/man-making-dosa.jpg",
  "https://honest-bite-be.s3.amazonaws.com/momos.jpg",
  "https://honest-bite-be.s3.amazonaws.com/orange-cheesecake.jpg",
  "https://honest-bite-be.s3.amazonaws.com/paneer-tikka.jpg",
  "https://honest-bite-be.s3.amazonaws.com/pasta.png",
  "https://honest-bite-be.s3.amazonaws.com/pav-bhaji.jpg",
  "https://honest-bite-be.s3.amazonaws.com/pho-vietnamese-noodle-soup.jpg",
  "https://honest-bite-be.s3.amazonaws.com/pizza.png",
  "https://honest-bite-be.s3.amazonaws.com/pizzaBanner.png",
  "https://honest-bite-be.s3.amazonaws.com/pretezel.jpg",
  "https://honest-bite-be.s3.amazonaws.com/ragda.jpg",
  "https://honest-bite-be.s3.amazonaws.com/ramen.jpg",
  "https://honest-bite-be.s3.amazonaws.com/rasmalai.jpg",
  "https://honest-bite-be.s3.amazonaws.com/samosa-jalebi.jpg",
  "https://honest-bite-be.s3.amazonaws.com/sandwich.jpg",
  "https://honest-bite-be.s3.amazonaws.com/south-indian-cook-with-masaladosa-.jpg",
  "https://honest-bite-be.s3.amazonaws.com/sushi-served-on-a-wooden.jpg",
  "https://honest-bite-be.s3.amazonaws.com/taco.jpg",
  "https://honest-bite-be.s3.amazonaws.com/tiramisu.jpg",
  "https://honest-bite-be.s3.amazonaws.com/vada-pav.png",
  "https://honest-bite-be.s3.amazonaws.com/waffle.jpg",
  "https://honest-bite-be.s3.amazonaws.com/watercolor-plate-of-fried-chicken.jpg",
];

// Function to randomly select 2 unique image URLs
const getRandomImages = () => {
  const shuffled = imageUrls.sort(() => 0.5 - Math.random());
  return shuffled.slice(0, 2); // Get two random images
};

// Array to hold the generated posts
const posts: Post[] = [];

for (let i = 0; i < 20; i++) {
  // Create a new data object for each post
  const data: Post = {
    img: getRandomImages(), // Get 2 random images for each post
    name: "test " + i,
    caption: "test post " + i,
    location: "mumbai " + i,
    likes: i + Math.floor(Math.random() * 100),
    comments: ["test comment 1", "test comment 2", "test comment 3"],
    shares: i + Math.floor(Math.random() * 100),
    bookmarked: Math.random() > 0.5,
    Dietary: Math.random() > 0.5 ? "veg" : "non-veg", // Randomize dietary preference
    Cuisine: Math.random() > 0.5 ? "italian" : "indian", // Static field
    mealType: Math.random() > 0.5 ? "dinner" : "lunch", // Static field
    tags: ["veg", "italian", "dinner"],
    createdAt: new Date(`2023-${(i % 12) + 1}-01`), // Ensure valid month
  };

  posts.push(data); // Store the post in the array
}

// Log the posts array to the console
console.log(JSON.stringify(posts, null, 2));
[
  {
    img: [
      "https://honest-bite-be.s3.amazonaws.com/biryani.jpg",
      "https://honest-bite-be.s3.amazonaws.com/creme-brulee.jpg",
    ],
    name: "test 0",
    caption: "test post 0",
    location: "mumbai 0",
    likes: 4,
    comments: ["test comment 1", "test comment 2", "test comment 3"],
    shares: 38,
    bookmarked: true,
    Dietary: "non-veg",
    Cuisine: "indian",
    mealType: "lunch",
    tags: ["veg", "italian", "dinner"],
    createdAt: "2022-12-31T18:30:00.000Z",
  },
  {
    img: [
      "https://honest-bite-be.s3.amazonaws.com/burger.jpg",
      "https://honest-bite-be.s3.amazonaws.com/pav-bhaji.jpg",
    ],
    name: "test 1",
    caption: "test post 1",
    location: "mumbai 1",
    likes: 24,
    comments: ["test comment 1", "test comment 2", "test comment 3"],
    shares: 17,
    bookmarked: true,
    Dietary: "non-veg",
    Cuisine: "italian",
    mealType: "lunch",
    tags: ["veg", "italian", "dinner"],
    createdAt: "2023-01-31T18:30:00.000Z",
  },
  {
    img: [
      "https://honest-bite-be.s3.amazonaws.com/QUESADILLA.jpg",
      "https://honest-bite-be.s3.amazonaws.com/fafafel.jpg",
    ],
    name: "test 2",
    caption: "test post 2",
    location: "mumbai 2",
    likes: 62,
    comments: ["test comment 1", "test comment 2", "test comment 3"],
    shares: 82,
    bookmarked: false,
    Dietary: "veg",
    Cuisine: "italian",
    mealType: "dinner",
    tags: ["veg", "italian", "dinner"],
    createdAt: "2023-02-28T18:30:00.000Z",
  },
  {
    img: [
      "https://honest-bite-be.s3.amazonaws.com/dhokla.jpg",
      "https://honest-bite-be.s3.amazonaws.com/biryani.jpg",
    ],
    name: "test 3",
    caption: "test post 3",
    location: "mumbai 3",
    likes: 59,
    comments: ["test comment 1", "test comment 2", "test comment 3"],
    shares: 95,
    bookmarked: true,
    Dietary: "veg",
    Cuisine: "italian",
    mealType: "lunch",
    tags: ["veg", "italian", "dinner"],
    createdAt: "2023-03-31T18:30:00.000Z",
  },
  {
    img: [
      "https://honest-bite-be.s3.amazonaws.com/waffle.jpg",
      "https://honest-bite-be.s3.amazonaws.com/pasta.png",
    ],
    name: "test 4",
    caption: "test post 4",
    location: "mumbai 4",
    likes: 94,
    comments: ["test comment 1", "test comment 2", "test comment 3"],
    shares: 86,
    bookmarked: true,
    Dietary: "non-veg",
    Cuisine: "italian",
    mealType: "lunch",
    tags: ["veg", "italian", "dinner"],
    createdAt: "2023-04-30T18:30:00.000Z",
  },
  {
    img: [
      "https://honest-bite-be.s3.amazonaws.com/waffle.jpg",
      "https://honest-bite-be.s3.amazonaws.com/man-making-dosa.jpg",
    ],
    name: "test 5",
    caption: "test post 5",
    location: "mumbai 5",
    likes: 62,
    comments: ["test comment 1", "test comment 2", "test comment 3"],
    shares: 22,
    bookmarked: true,
    Dietary: "non-veg",
    Cuisine: "italian",
    mealType: "dinner",
    tags: ["veg", "italian", "dinner"],
    createdAt: "2023-05-31T18:30:00.000Z",
  },
  {
    img: [
      "https://honest-bite-be.s3.amazonaws.com/biryani.jpg",
      "https://honest-bite-be.s3.amazonaws.com/creme-brulee.jpg",
    ],
    name: "test 6",
    caption: "test post 6",
    location: "mumbai 6",
    likes: 13,
    comments: ["test comment 1", "test comment 2", "test comment 3"],
    shares: 99,
    bookmarked: false,
    Dietary: "veg",
    Cuisine: "italian",
    mealType: "dinner",
    tags: ["veg", "italian", "dinner"],
    createdAt: "2023-06-30T18:30:00.000Z",
  },
  {
    img: [
      "https://honest-bite-be.s3.amazonaws.com/biryani.jpg",
      "https://honest-bite-be.s3.amazonaws.com/creme-brulee.jpg",
    ],
    name: "test 7",
    caption: "test post 7",
    location: "mumbai 7",
    likes: 49,
    comments: ["test comment 1", "test comment 2", "test comment 3"],
    shares: 100,
    bookmarked: true,
    Dietary: "non-veg",
    Cuisine: "indian",
    mealType: "lunch",
    tags: ["veg", "italian", "dinner"],
    createdAt: "2023-07-31T18:30:00.000Z",
  },
  {
    img: [
      "https://honest-bite-be.s3.amazonaws.com/vada-pav.png",
      "https://honest-bite-be.s3.amazonaws.com/biryani.jpg",
    ],
    name: "test 8",
    caption: "test post 8",
    location: "mumbai 8",
    likes: 82,
    comments: ["test comment 1", "test comment 2", "test comment 3"],
    shares: 11,
    bookmarked: false,
    Dietary: "veg",
    Cuisine: "italian",
    mealType: "dinner",
    tags: ["veg", "italian", "dinner"],
    createdAt: "2023-08-31T18:30:00.000Z",
  },
  {
    img: [
      "https://honest-bite-be.s3.amazonaws.com/dosa.jpg",
      "https://honest-bite-be.s3.amazonaws.com/samosa-jalebi.jpg",
    ],
    name: "test 9",
    caption: "test post 9",
    location: "mumbai 9",
    likes: 61,
    comments: ["test comment 1", "test comment 2", "test comment 3"],
    shares: 62,
    bookmarked: true,
    Dietary: "veg",
    Cuisine: "italian",
    mealType: "lunch",
    tags: ["veg", "italian", "dinner"],
    createdAt: "2023-10-01T00:00:00.000Z",
  },
  {
    img: [
      "https://honest-bite-be.s3.amazonaws.com/momos.jpg",
      "https://honest-bite-be.s3.amazonaws.com/pizzaBanner.png",
    ],
    name: "test 10",
    caption: "test post 10",
    location: "mumbai 10",
    likes: 34,
    comments: ["test comment 1", "test comment 2", "test comment 3"],
    shares: 65,
    bookmarked: false,
    Dietary: "non-veg",
    Cuisine: "indian",
    mealType: "dinner",
    tags: ["veg", "italian", "dinner"],
    createdAt: "2023-11-01T00:00:00.000Z",
  },
  {
    img: [
      "https://honest-bite-be.s3.amazonaws.com/south-indian-cook-with-masaladosa-.jpg",
      "https://honest-bite-be.s3.amazonaws.com/paneer-tikka.jpg",
    ],
    name: "test 11",
    caption: "test post 11",
    location: "mumbai 11",
    likes: 18,
    comments: ["test comment 1", "test comment 2", "test comment 3"],
    shares: 69,
    bookmarked: false,
    Dietary: "veg",
    Cuisine: "indian",
    mealType: "dinner",
    tags: ["veg", "italian", "dinner"],
    createdAt: "2023-12-01T00:00:00.000Z",
  },
  {
    img: [
      "https://honest-bite-be.s3.amazonaws.com/waffle.jpg",
      "https://honest-bite-be.s3.amazonaws.com/dhokla.jpg",
    ],
    name: "test 12",
    caption: "test post 12",
    location: "mumbai 12",
    likes: 110,
    comments: ["test comment 1", "test comment 2", "test comment 3"],
    shares: 23,
    bookmarked: false,
    Dietary: "non-veg",
    Cuisine: "italian",
    mealType: "dinner",
    tags: ["veg", "italian", "dinner"],
    createdAt: "2022-12-31T18:30:00.000Z",
  },
  {
    img: [
      "https://honest-bite-be.s3.amazonaws.com/paneer-tikka.jpg",
      "https://honest-bite-be.s3.amazonaws.com/waffle.jpg",
    ],
    name: "test 13",
    caption: "test post 13",
    location: "mumbai 13",
    likes: 13,
    comments: ["test comment 1", "test comment 2", "test comment 3"],
    shares: 49,
    bookmarked: true,
    Dietary: "non-veg",
    Cuisine: "indian",
    mealType: "dinner",
    tags: ["veg", "italian", "dinner"],
    createdAt: "2023-01-31T18:30:00.000Z",
  },
  {
    img: [
      "https://honest-bite-be.s3.amazonaws.com/alfajor-latino.jpg",
      "https://honest-bite-be.s3.amazonaws.com/ramen.jpg",
    ],
    name: "test 14",
    caption: "test post 14",
    location: "mumbai 14",
    likes: 95,
    comments: ["test comment 1", "test comment 2", "test comment 3"],
    shares: 100,
    bookmarked: true,
    Dietary: "veg",
    Cuisine: "indian",
    mealType: "lunch",
    tags: ["veg", "italian", "dinner"],
    createdAt: "2023-02-28T18:30:00.000Z",
  },
  {
    img: [
      "https://honest-bite-be.s3.amazonaws.com/FF.png",
      "https://honest-bite-be.s3.amazonaws.com/sushi-served-on-a-wooden.jpg",
    ],
    name: "test 15",
    caption: "test post 15",
    location: "mumbai 15",
    likes: 102,
    comments: ["test comment 1", "test comment 2", "test comment 3"],
    shares: 64,
    bookmarked: false,
    Dietary: "veg",
    Cuisine: "italian",
    mealType: "lunch",
    tags: ["veg", "italian", "dinner"],
    createdAt: "2023-03-31T18:30:00.000Z",
  },
  {
    img: [
      "https://honest-bite-be.s3.amazonaws.com/alfajor-latino.jpg",
      "https://honest-bite-be.s3.amazonaws.com/pizza.png",
    ],
    name: "test 16",
    caption: "test post 16",
    location: "mumbai 16",
    likes: 52,
    comments: ["test comment 1", "test comment 2", "test comment 3"],
    shares: 73,
    bookmarked: true,
    Dietary: "veg",
    Cuisine: "indian",
    mealType: "dinner",
    tags: ["veg", "italian", "dinner"],
    createdAt: "2023-04-30T18:30:00.000Z",
  },
  {
    img: [
      "https://honest-bite-be.s3.amazonaws.com/south-indian-cook-with-masaladosa-.jpg",
      "https://honest-bite-be.s3.amazonaws.com/samosa-jalebi.jpg",
    ],
    name: "test 17",
    caption: "test post 17",
    location: "mumbai 17",
    likes: 80,
    comments: ["test comment 1", "test comment 2", "test comment 3"],
    shares: 102,
    bookmarked: true,
    Dietary: "veg",
    Cuisine: "indian",
    mealType: "lunch",
    tags: ["veg", "italian", "dinner"],
    createdAt: "2023-05-31T18:30:00.000Z",
  },
  {
    img: [
      "https://honest-bite-be.s3.amazonaws.com/paneer-tikka.jpg",
      "https://honest-bite-be.s3.amazonaws.com/rasmalai.jpg",
    ],
    name: "test 18",
    caption: "test post 18",
    location: "mumbai 18",
    likes: 47,
    comments: ["test comment 1", "test comment 2", "test comment 3"],
    shares: 39,
    bookmarked: false,
    Dietary: "non-veg",
    Cuisine: "indian",
    mealType: "dinner",
    tags: ["veg", "italian", "dinner"],
    createdAt: "2023-06-30T18:30:00.000Z",
  },
  {
    img: [
      "https://honest-bite-be.s3.amazonaws.com/tiramisu.jpg",
      "https://honest-bite-be.s3.amazonaws.com/apple-pie.jpg",
    ],
    name: "test 19",
    caption: "test post 19",
    location: "mumbai 19",
    likes: 38,
    comments: ["test comment 1", "test comment 2", "test comment 3"],
    shares: 106,
    bookmarked: false,
    Dietary: "non-veg",
    Cuisine: "indian",
    mealType: "lunch",
    tags: ["veg", "italian", "dinner"],
    createdAt: "2023-07-31T18:30:00.000Z",
  },
];
